### ISSUE TITLE
Both upickle and ujson have security vulnerablities

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/toolkit#1]
Please, see https://github.com/com-lihaoyi/upickle/issues/416#issuecomment-1346151961

**Comment by szymon-rd** [comment]
Hi! Thank you for creating the issue. We are aware, and it's important for us to address it with the library maintainers. I will keep this issue as a place to post updates.

**Comment by plokhotnyuk** [comment]
Fixed in upickle v3.0.0 https://github.com/com-lihaoyi/upickle/releases/tag/3.0.0

**Comment by bishabosha** [comment]
I don't think this should be closed until the patched version is part of the build?

**Comment by plokhotnyuk** [comment]
@bishabosha You are right.

Also, need to check for other possible vulnerabilities like DoS by parsing of too big numbers or too deeply nested JSON arrays/objects.
