### ISSUE TITLE
Testing framework dependencies

### ISSUE THREAD

**Issue by bishabosha** [scala/toolkit#13]
Currently the published artefact of `org.scala-lang:toolkit_3:0.1.6` includes MUnit as a dependency.

questions arise:
- could it be a problem to include MUnit always (e.g. should libraries be published with toolkit as a dependency)
- assuming POM files can't scope dependencies, should there be a separate "test" toolkit artefact (with support from scala-cli to add the correct dependency for either main/test scope)

**Comment by szymon-rd** [comment]
I think we will try to implement this scoped approach: In Scala-CLI `//> using "toolkit" ...` will add dependency to `toolkit` for main scope, and `toolkit-test` for the test scope. `Toolkit-test` will be a newly created artifact containing, at this point, only a transitive dependency to `munit`.

**Comment by szymon-rd** [comment]
Resolved in https://github.com/VirtusLab/scala-cli/pull/2127#event-9304215596
