### ISSUE TITLE
New toolkit release with updates?

### ISSUE THREAD

**Issue by armanbilge** [scala/toolkit#33]
sttp has released 4.0.0-M5 and upickle has released 3.1.3

https://github.com/scala/toolkit/blob/758c63e2752b837dc02ce1cb1d1874890bd64ee3/Toolkit.scala#L3-L6

munit has released 1.0.0-M10

https://github.com/scala/toolkit/blob/758c63e2752b837dc02ce1cb1d1874890bd64ee3/ToolkitTest.scala#L3

**Comment by bishabosha** [comment]
We should probably implement some sort of automatic scanning of dependencies

**Comment by szymon-rd** [comment]
The problem with milestones on major versions is that they can be breaking in the same way as major releases. So, in theory, we should release toolkit 1.0 when bumping the milestone major. However, as we are in 0.x, if there are no breaking changes, I think we can go around that and release a minor/patch.

**Comment by szymon-rd** [comment]
Release triggered https://github.com/scala/toolkit/actions/runs/6561905955
