### ISSUE TITLE
Version of sttp in toolkit is old

### ISSUE THREAD

**Issue by SethTisue** [scala/toolkit#45]
`Toolkit.scala` has:

```
//> using dep com.softwaremill.sttp.client4::core::4.0.0-M6
//> using dep com.softwaremill.sttp.client4::upickle::4.0.0-M6
```

but the latest is https://index.scala-lang.org/softwaremill/sttp/artifacts/core/4.0.0-M13

**Comment by SethTisue** [comment]
note that when it's updated, it's also necessary to update the Toolkit tutorials, which include version numbers

so for example at https://github.com/scala/docs.scala-lang/pull/3015 we see that the tutorials were still suggesting M1 because apparently there is no process in place to update that

**Comment by adpi2** [comment]
> so for example at https://github.com/scala/docs.scala-lang/pull/3015 we see that the tutorials were still suggesting M1 because apparently there is no process in place to update that

No we don't have such process yet. I am going to add myself a reminder to do the updates and releases once every month, to not burden anyone else.

**Comment by SethTisue** [comment]
Monthly SGTM 👍
