### ISSUE TITLE
Missing native artifacts for `toolkit-test` 0.3.0

### ISSUE THREAD

**Issue by Gedochao** [scala/toolkit#49]
So it seems Scala Native artifacts for `toolkit-test` 0.3.0 were never released. 
This is a bit of an issue, since this is the last version supporting Scala Native 0.4.x.

https://mvnrepository.com/artifact/org.scala-lang/toolkit-test

![image](https://github.com/scala/toolkit/assets/18601388/92728f40-3326-47bc-bc63-8412d0775f0a)

This makes 0.3.0 virtually unusable with Scala CLI (unless one explicitly only depends on the main scope, rather than the dynamic integrations).
```bash
scala-cli -e 'println(os.pwd)' --toolkit 0.3.0 --native --native-version 0.4.17
# Downloading 4 dependencies and 2 internal dependencies
# [error]  Error downloading org.scala-lang:toolkit-test_native0.4_3:0.3.0
# [error]   not found: /Users/pchabelski/.ivy2/local/org.scala-lang/toolkit-test_native0.4_3/0.3.0/ivys/ivy.xml
# [error]   not found: https://repo1.maven.org/maven2/org/scala-lang/toolkit-test_native0.4_3/0.3.0/toolkit-test_native0.4_3-0.3.0.pom
# [error]   not found: /Users/pchabelski/Library/Caches/ScalaCli/local-repo/1.3.2/org.scala-lang/toolkit-test_native0.4_3/0.3.0/ivys/ivy.xml
# [error]   No fallback URL found
# [error] COMMAND_LINE
```

The last working version is 0.2.1.
```bash
scala-cli -e 'println(os.pwd)' --toolkit 0.2.1 --native --native-version 0.4.17
# Compiling project (Scala 3.4.2, Scala Native 0.4.17)
# Compiled project (Scala 3.4.2, Scala Native 0.4.17)
# [hint]  "toolkit is outdated, update to 0.3.0"
# [hint]      toolkit 0.2.1 -> 0.3.0
# [hint] COMMAND_LINE
# [info] Linking (895 ms)
# [info] Checking intermediate code (quick) (82 ms)
# [info] Discovered 888 classes and 5298 methods
# [info] Optimizing (debug mode) (795 ms)
# [info] Generating intermediate code (628 ms)
# [info] Produced 10 files
# [info] Compiling to native code (1780 ms)
# [info] Linking with [pthread, dl]
# [info] Total (4301 ms)
# /Users/pchabelski/Downloads
```

**Comment by adpi2** [comment]
Thanks for reporting!

**Comment by adpi2** [comment]
Something went wrong in the [CI job](https://github.com/scala/toolkit/actions/runs/9092290189/job/24988687122).

I fixed that by republishing manually:
https://oss.sonatype.org/content/repositories/public/org/scala-lang/toolkit-test_native0.4_2.13/0.3.0/

The artifact will soon land at https://repo1.maven.org/maven2/org/scala-lang/toolkit-test_native0.4_2.13/0.3.0/
